repeat wait()
until game:IsLoaded()
pcall(function()
	Nexus_Version = 101
	loadstring(game:HttpGet'https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua')()
	Nexus:Connect()
end)
wait(0.1)
pcall(function()
	Nexus_Version = 101
	loadstring(game:HttpGet'https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua')()
	Nexus:Connect()
end)
wait(0.1)
pcall(function()
	Nexus_Version = 101
	loadstring(game:HttpGet'https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua')()
	Nexus:Connect()
end)
wait(0.1)
pcall(function()
	Nexus_Version = 101
	loadstring(game:HttpGet'https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua')()
	Nexus:Connect()
end)
wait(0.1)
pcall(function()
	Nexus_Version = 101
	loadstring(game:HttpGet'https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua')()
	Nexus:Connect()
end)
wait(5)
pcall(function()
	Nexus_Version = 101
	loadstring(game:HttpGet'https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua')()
	Nexus:Connect()
end)
wait(10)
pcall(function()
	Nexus_Version = 101
	loadstring(game:HttpGet'https://raw.githubusercontent.com/ic3w0lf22/Roblox-Account-Manager/master/RBX%20Alt%20Manager/Nexus/Nexus.lua')()
	Nexus:Connect()
end)
